### ISSUE TITLE
Season 3 Checklist

### ISSUE THREAD

**Issue by Blaylock1988** [GV-Kharak/GVK-AlphaKharak-Settings#118]
- [x] Publish Planet Mod 
- [x] Publish static drills Mod
- [x] Publish Settings Mod
- [x] Publish Weapons Mod
- [x] Publish Derelicts Mod
- [x] Reset Voxels
- [x] Clear safezones (N1Ran shitty plugin)
- [x] Set up topgrid plugin #99 
- [x] Respawn all static encounters
- [x] See if vanilla limiter can do grid sizes
- [x] Adjust KOTH settings
- [x] Set Territories settings
- [x] increase rewards SC payout (if WC compatibility done)
- [x] Clear known steam IDs
- [x] Purge players in SE
- [x] Purge NPC factions
- [x] Delete Grid Backups
- [x] Delete Hangar
- [x] Delete mod content
- [x] Adjust MES configs
- [x] Clear server logs
- [x] Clear clear mod content logs
- [x] Update MOTD
- [x] Ensure Rachel S'Jet has funds for trade

**Comment by Blaylock1988** [comment]
Updated for Season 3
